trigger: none

pool:
  name: Default

parameters:
  - name: workingDirectory
    type: string
    default: "./iac/backend"
      
variables:
  - group: "springboot-react"

stages:
- stage: backendDeployment
  displayName: "Terraform Backend Deployment"
  jobs:
  - job: deployBackend
    displayName: "Deploy Terraform Backend"
    steps:
      # Install Azure CLI
      - script: |
          echo "Installing Azure CLI..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash
          az version
        displayName: "Install Azure CLI"

      # Azure CLI Login
      - script: |
          az login --service-principal \
          --username $(clientId) \
          --password $(clientSecret) \
          --tenant $(tenantId)
        displayName: "Azure CLI Login"
        workingDirectory: ${{parameters.workingDirectory}}

      # Run your custom shell script
      - script: |
          echo "Making script executable"
          chmod +x ./st_backend.sh

          echo "Running script"
          ./st_backend.sh
        displayName: "Deploy Resource Group, Storage with Container"
        workingDirectory: ${{parameters.workingDirectory}}
